<a href="https://colab.research.google.com/github/chonginbilly/Moringa_DS/blob/Moringa_python/Importing_Data_Using_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<font color="green">*To start working on this notebook, or any other notebook that we will use in this course, we will need to save our own copy of it. We can do this by clicking File > Save a Copy in Drive. We will then be able to make edits to our own copy of this notebook.*</font>

---

# Importing Data Using Pandas

## Introduction

In this lesson, we will actively focus on mastering the skill of importing data using Pandas. Throughout this session, we will meticulously explore how to read various data file formats, such as CSV, Excel, JSON, text, and more, transforming them into Pandas DataFrames. Additionally, we will delve into the essential knowledge of exporting Pandas DataFrames to files. Join us as we enhance our proficiency in handling diverse datasets with Pandas.

## Objectives

By the end of this lesson, you will be able to:
- Read and import diverse data files, including CSV, Excel, JSON, and text, into Pandas DataFrames.
- Employ various Pandas functions to manipulate and preprocess imported data effectively.
- Export Pandas DataFrames to different file formats, ensuring seamless data sharing and storage.

## Loading Pandas Library

In [ ]:
import pandas as pd

# operating system dependent functionality
import os

## Mounting google drive

In [ ]:
from google.colab import drive

# mount your google drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# path to data folder
data_folder = "/content/drive/MyDrive/Product/Naivas Big Data /Data/csv"

# Change the current working directory to the specified path
os.chdir(data_folder)

# List files in the directory
files = os.listdir()
print("Files in the directory:", files)

Files in the directory: ['results.csv', 'ACS_16_5YR_B24011_with_ann.csv', 'Yelp_Reviews_Corrupt.csv', 'bp.txt', 'africa_capitals.csv', 'Yelp_Selected_Businesses.xlsx', 'NewSavedView.csv', 'NewSavedView.xlsx', 'Zipcode_Demos.csv']

In [ ]:
# the current working directory
os.getcwd()

'/content/drive/MyDrive/Product/Naivas Big Data /Data/csv'

## Importing Data

Letâ€™s explore the fundamental process of reading data into Pandas DataFrames. Whether it's a CSV file, Excel spreadsheet, JSON file, or plain text, understanding how to import diverse datasets is crucial for effective data analysis. We'll start by focusing on the common scenario of reading CSV files, laying the groundwork for subsequent discussions on other file formats. This fundamental skill forms the basis for efficient data manipulation and exploration using Pandas.
There are a few main functions for importing data into a Pandas DataFrame including:
- `pd.read_csv()`
- `pd.read_excel()`
- `pd.read_json()`
- `pd.DataFrame.from_dict()`

Most of these functions are fairly straightforward; we use `read_csv()` for **csv files**, `read_excel()` for **excel files**, and `read_json()` for **json files**.

## Reading CSV files

CSV (Comma-Separated Values) files are a common and widely used format for storing tabular data. They consist of rows and columns, with each line representing a row and values within each row separated by commas. Pandas provides the `pd.read_csv()` function to effortlessly read data from CSV files and convert it into a DataFrame.
To read a CSV file into a Pandas DataFrame, we simply need to provide the file path as an argument to the `read_csv()` function. For example:

In [ ]:
# loading the results.csv file
df = pd.read_csv("results.csv")
df.head()

,Gender,Event,Location,Year,Medal,Name,Nationality,Result
0,M,10000M Men,Rio,2016,G,Mohamed FARAH,USA,25:05.17
1,M,10000M Men,Rio,2016,S,Paul Kipngetich TANUI,KEN,27:05.64
2,M,10000M Men,Rio,2016,B,Tamirat TOLA,ETH,27:06.26
3,M,10000M Men,Beijing,2008,G,Kenenisa BEKELE,ETH,27:01.17
4,M,10000M Men,Beijing,2008,S,Sileshi SIHINE,ETH,27:02.77

The `read_csv()` function, which extends beyond traditional comma-separated values (CSV) files. This method can be employed for any plain-text delimited file, encompassing various formats such as pipe `(|)` delimited files `(.psv)` and tab-separated files `(.tsv)`.
To illustrate, let's investigate a text file, `bp.txt`, stored in the `csv` folder:

In [ ]:
# Import 'bp.txt' file

df = pd.read_csv('bp.txt', delimiter='\t')
df.head()

   Pt   BP  Age  Weight   BSA  Dur  Pulse  Stress
0   1  105   47    85.4  1.75  5.1     63      33
1   2  115   49    94.2  2.10  3.8     70      14
2   3  116   49    95.3  1.98  8.2     72      10
3   4  117   50    94.7  2.01  5.8     73      99
4   5  112   51    89.4  1.89  7.0     72      95

### Skipping and Limiting Rows

When working with large datasets, it's often beneficial to skip or limit the number of rows read into a Pandas DataFrame. The `pd.read_csv()` function provides parameters to facilitate this:

**Skipping Rows:**

We can skip a specified number of rows at the beginning of the file using the `skiprows` parameter. This is particularly useful when dealing with files that contain header information or unnecessary lines at the beginning.

In [ ]:
# Import the first 100 rows of 'ACS_16_5YR_B24011_with_ann.csv' file

df = pd.read_csv('ACS_16_5YR_B24011_with_ann.csv', nrows=100)

# Look at the first five rows

df.head()

,GEO.id,GEO.id2,GEO.display-label,HD01_VD01,HD02_VD01,HD01_VD02,HD02_VD02,HD01_VD03,HD02_VD03,HD01_VD04,...,HD01_VD32,HD02_VD32,HD01_VD33,HD02_VD33,HD01_VD34,HD02_VD34,HD01_VD35,HD02_VD35,HD01_VD36,HD02_VD36
0,Id,Id2,Geography,Estimate; Total:,Margin of Error; Total:,"Estimate; Total: - Management, business, scien...","Margin of Error; Total: - Management, business...","Estimate; Total: - Management, business, scien...","Margin of Error; Total: - Management, business...","Estimate; Total: - Management, business, scien...",...,"Estimate; Total: - Natural resources, construc...","Margin of Error; Total: - Natural resources, c...","Estimate; Total: - Production, transportation,...","Margin of Error; Total: - Production, transpor...","Estimate; Total: - Production, transportation,...","Margin of Error; Total: - Production, transpor...","Estimate; Total: - Production, transportation,...","Margin of Error; Total: - Production, transpor...","Estimate; Total: - Production, transportation,...","Margin of Error; Total: - Production, transpor..."
1,0500000US01001,01001,"Autauga County, Alabama",33267,2306,48819,1806,55557,4972,63333,...,31402,5135,35594,3034,36059,3893,47266,13608,19076,4808
2,0500000US01003,01003,"Baldwin County, Alabama",31540,683,49524,1811,57150,6980,63422,...,35603,3882,30549,1606,29604,4554,35504,6260,24182,3580
3,0500000US01005,01005,"Barbour County, Alabama",26575,1653,41652,2638,51797,5980,52775,...,37847,11189,26094,4884,25339,4900,37282,6017,16607,3497
4,0500000US01007,01007,"Bibb County, Alabama",30088,2224,40787,2896,50069,12841,67917,...,45952,5622,28983,3401,31881,2317,26580,2901,23479,4942

Notice the first row is descriptions of the variables

In [ ]:
# Skip the first row
df_skip_rows = pd.read_csv('ACS_16_5YR_B24011_with_ann.csv', skiprows=1, nrows=100)
df_skip_rows.head()

,Id,Id2,Geography,Estimate; Total:,Margin of Error; Total:,"Estimate; Total: - Management, business, science, and arts occupations:","Margin of Error; Total: - Management, business, science, and arts occupations:","Estimate; Total: - Management, business, science, and arts occupations: - Management, business, and financial occupations:","Margin of Error; Total: - Management, business, science, and arts occupations: - Management, business, and financial occupations:","Estimate; Total: - Management, business, science, and arts occupations: - Management, business, and financial occupations: - Management occupations",...,"Estimate; Total: - Natural resources, construction, and maintenance occupations: - Installation, maintenance, and repair occupations","Margin of Error; Total: - Natural resources, construction, and maintenance occupations: - Installation, maintenance, and repair occupations","Estimate; Total: - Production, transportation, and material moving occupations:","Margin of Error; Total: - Production, transportation, and material moving occupations:","Estimate; Total: - Production, transportation, and material moving occupations: - Production occupations","Margin of Error; Total: - Production, transportation, and material moving occupations: - Production occupations","Estimate; Total: - Production, transportation, and material moving occupations: - Transportation occupations","Margin of Error; Total: - Production, transportation, and material moving occupations: - Transportation occupations","Estimate; Total: - Production, transportation, and material moving occupations: - Material moving occupations","Margin of Error; Total: - Production, transportation, and material moving occupations: - Material moving occupations"
0,0500000US01001,1001,"Autauga County, Alabama",33267,2306,48819,1806,55557,4972,63333,...,31402,5135,35594,3034,36059,3893,47266,13608,19076,4808
1,0500000US01003,1003,"Baldwin County, Alabama",31540,683,49524,1811,57150,6980,63422,...,35603,3882,30549,1606,29604,4554,35504,6260,24182,3580
2,0500000US01005,1005,"Barbour County, Alabama",26575,1653,41652,2638,51797,5980,52775,...,37847,11189,26094,4884,25339,4900,37282,6017,16607,3497
3,0500000US01007,1007,"Bibb County, Alabama",30088,2224,40787,2896,50069,12841,67917,...,45952,5622,28983,3401,31881,2317,26580,2901,23479,4942
4,0500000US01009,1009,"Blount County, Alabama",34900,2063,46593,2963,47003,6189,50991,...,42489,7176,32969,3767,31814,4551,41375,5280,26755,2963

In this example, the first row of the CSV file are skipped during the import process.

**Limiting Rows:**

To read only a specific number of rows from the beginning of the file, you can use the `nrows` parameter. This is helpful when you're interested in working with a subset of the data.

In [ ]:
# Read only the first 100 rows of the CSV file
df_limit_rows = pd.read_csv('ACS_16_5YR_B24011_with_ann.csv', nrows=100)

df_limit_rows.shape

(100, 75)

Here, the DataFrame `df_limit_rows` will contain only the first 100 rows of the CSV file.

These functionalities enhance the efficiency of data import by allowing you to focus on the relevant portions of the dataset, skipping unnecessary rows or limiting the import to a manageable subset.

In an ideal world, we would want to drop the row containing the description of the data, and this is how to do it:

In [ ]:
df = pd.read_csv('ACS_16_5YR_B24011_with_ann.csv', nrows=100)

df.drop(0, inplace=True)

df.head()

,GEO.id,GEO.id2,GEO.display-label,HD01_VD01,HD02_VD01,HD01_VD02,HD02_VD02,HD01_VD03,HD02_VD03,HD01_VD04,...,HD01_VD32,HD02_VD32,HD01_VD33,HD02_VD33,HD01_VD34,HD02_VD34,HD01_VD35,HD02_VD35,HD01_VD36,HD02_VD36
1,0500000US01001,01001,"Autauga County, Alabama",33267,2306,48819,1806,55557,4972,63333,...,31402,5135,35594,3034,36059,3893,47266,13608,19076,4808
2,0500000US01003,01003,"Baldwin County, Alabama",31540,683,49524,1811,57150,6980,63422,...,35603,3882,30549,1606,29604,4554,35504,6260,24182,3580
3,0500000US01005,01005,"Barbour County, Alabama",26575,1653,41652,2638,51797,5980,52775,...,37847,11189,26094,4884,25339,4900,37282,6017,16607,3497
4,0500000US01007,01007,"Bibb County, Alabama",30088,2224,40787,2896,50069,12841,67917,...,45952,5622,28983,3401,31881,2317,26580,2901,23479,4942
5,0500000US01009,01009,"Blount County, Alabama",34900,2063,46593,2963,47003,6189,50991,...,42489,7176,32969,3767,31814,4551,41375,5280,26755,2963

### Header

The `header` parameter in the `pd.read_csv()` function is crucial for handling the presence of **headers** or **column names** in the CSV file. By default, Pandas assumes the **first row of the file contains column names**. However, in some cases, the file might not have a header, or the header might be present in a different row.

It does specifies the row where column names are and starts importing data from that point:

In [ ]:
# Look at the error output once you run this cell. What type of error is it?
df = pd.read_csv('ACS_16_5YR_B24011_with_ann.csv', header=1)
df.head()

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 23033: invalid continuation byte

### Encoding

The encoding parameter in the `pd.read_csv()` function addresses the character encoding used in the CSV file. Character encoding specifies how characters are represented as bytes in a file, and choosing the correct encoding is crucial for interpreting the text accurately.

Encoding errors like the one above are always frustrating. This has to do with how the strings within the file itself are formatted. The most common encoding other than `utf-8` that we are likely to come across is `latin-1`.

In [ ]:
# Import the 'ACS_16_5YR_B24011_with_ann.csv' file using a proper encoding

df = pd.read_csv('ACS_16_5YR_B24011_with_ann.csv', header=1, encoding='latin-1')

df.head()

,Id,Id2,Geography,Estimate; Total:,Margin of Error; Total:,"Estimate; Total: - Management, business, science, and arts occupations:","Margin of Error; Total: - Management, business, science, and arts occupations:","Estimate; Total: - Management, business, science, and arts occupations: - Management, business, and financial occupations:","Margin of Error; Total: - Management, business, science, and arts occupations: - Management, business, and financial occupations:","Estimate; Total: - Management, business, science, and arts occupations: - Management, business, and financial occupations: - Management occupations",...,"Estimate; Total: - Natural resources, construction, and maintenance occupations: - Installation, maintenance, and repair occupations","Margin of Error; Total: - Natural resources, construction, and maintenance occupations: - Installation, maintenance, and repair occupations","Estimate; Total: - Production, transportation, and material moving occupations:","Margin of Error; Total: - Production, transportation, and material moving occupations:","Estimate; Total: - Production, transportation, and material moving occupations: - Production occupations","Margin of Error; Total: - Production, transportation, and material moving occupations: - Production occupations","Estimate; Total: - Production, transportation, and material moving occupations: - Transportation occupations","Margin of Error; Total: - Production, transportation, and material moving occupations: - Transportation occupations","Estimate; Total: - Production, transportation, and material moving occupations: - Material moving occupations","Margin of Error; Total: - Production, transportation, and material moving occupations: - Material moving occupations"
0,0500000US01001,1001,"Autauga County, Alabama",33267,2306,48819,1806,55557,4972,63333,...,31402,5135,35594,3034,36059,3893,47266,13608,19076,4808
1,0500000US01003,1003,"Baldwin County, Alabama",31540,683,49524,1811,57150,6980,63422,...,35603,3882,30549,1606,29604,4554,35504,6260,24182,3580
2,0500000US01005,1005,"Barbour County, Alabama",26575,1653,41652,2638,51797,5980,52775,...,37847,11189,26094,4884,25339,4900,37282,6017,16607,3497
3,0500000US01007,1007,"Bibb County, Alabama",30088,2224,40787,2896,50069,12841,67917,...,45952,5622,28983,3401,31881,2317,26580,2901,23479,4942
4,0500000US01009,1009,"Blount County, Alabama",34900,2063,46593,2963,47003,6189,50991,...,42489,7176,32969,3767,31814,4551,41375,5280,26755,2963

#### Handling Encoding Errors:

The `errors` parameter allows you to handle encoding errors by either `replace`, `ignore`, or `strict`. `replace` replaces invalid characters with a replacement character, `ignore` skips invalid characters, and `strict` raises an error.

### Index Column

In Pandas, the `index_col` parameter within the `pd.read_csv()` function allows us to explicitly specify a column that should be used as the index of the resulting DataFrame.

**Default Behavior:**

In [ ]:
# Reading a CSV file with the default integer index
df_default_index = pd.read_csv('africa_capitals.csv')
df_default_index.head()

   Unnamed: 0       Country      Capital
0           1       Algeria      Algiers
1           2        Angola       Luanda
2           3         Benin   Porto-Novo
3           4      Botswana     Gaborone
4           5  Burkina Faso  Ouagadougou

 By default, Pandas assigns an integer index to the DataFrame.

**Specifying Index Column:**

In [ ]:
# Reading a CSV file with a specific column as the index
df_custom_index = pd.read_csv('africa_capitals.csv', index_col=0)
df_custom_index.head()

        Country      Capital
1       Algeria      Algiers
2        Angola       Luanda
3         Benin   Porto-Novo
4      Botswana     Gaborone
5  Burkina Faso  Ouagadougou

The `index_col` parameter allows us to designate a specific column to serve as the index.

### Skip Bad Lines

The `error_bad_lines` parameter in the `pd.read_csv()` function is used to handle lines in a CSV file that contain a different number of fields than expected. When set to `True` (default), encountering such lines raises a `ParserError` and stops the reading process. However, setting `error_bad_lines=False` instructs Pandas to skip lines with too many fields and continue reading the file.

Here's how we can use the `error_bad_lines` parameter:

In [ ]:
# using the error_bad_lines parameter
df = pd.read_csv("Yelp_Reviews_Corrupt.csv", error_bad_lines=False)

<ipython-input-16-79e04fef0fe6>:2: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df = pd.read_csv("Yelp_Reviews_Corrupt.csv", error_bad_lines=False)
Skipping line 2331: expected 10 fields, saw 11
Skipping line 2340: expected 10 fields, saw 12
Skipping line 2341: expected 10 fields, saw 13
Skipping line 2343: expected 10 fields, saw 18
Skipping line 2349: expected 10 fields, saw 12
Skipping line 2350: expected 10 fields, saw 16
Skipping line 2352: expected 10 fields, saw 12
Skipping line 2358: expected 10 fields, saw 13
Skipping line 2359: expected 10 fields, saw 11
Skipping line 2379: expected 10 fields, saw 11
Skipping line 2381: expected 10 fields, saw 12
Skipping line 2382: expected 10 fields, saw 12
Skipping line 2384: expected 10 fields, saw 11
Skipping line 2386: expected 10 fields, saw 12
Skipping line 2388: expected 10 fields, saw 12
Skipping line 2389: expected 10 fields, saw 13
Skipping line 2392: expected 10 fields, saw 15
Skipping line 2393: expected 10 fields, saw 18
Skipping line 2394: expected 10 fields, saw 15
Skipping line 2407: expected 10 fields, saw 12
Skipping line 2427: expected 10 fields, saw 11
Skipping line 2430: expected 10 fields, saw 12
Skipping line 2438: expected 10 fields, saw 17
Skipping line 2439: expected 10 fields, saw 11
Skipping line 2440: expected 10 fields, saw 11
Skipping line 2441: expected 10 fields, saw 11
Skipping line 2442: expected 10 fields, saw 12
Skipping line 2445: expected 10 fields, saw 13
Skipping line 2446: expected 10 fields, saw 12
Skipping line 2473: expected 10 fields, saw 13
Skipping line 2474: expected 10 fields, saw 11
Skipping line 2475: expected 10 fields, saw 12
Skipping line 2485: expected 10 fields, saw 12
Skipping line 2487: expected 10 fields, saw 15
Skipping line 2488: expected 10 fields, saw 11
Skipping line 2496: expected 10 fields, saw 20
Skipping line 2504: expected 10 fields, saw 13
Skipping line 2505: expected 10 fields, saw 13
Skipping line 2507: expected 10 fields, saw 11
Skipping line 2521: expected 10 fields, saw 15
Skipping line 2522: expected 10 fields, saw 12
Skipping line 2525: expected 10 fields, saw 13
Skipping line 2533: expected 10 fields, saw 12
Skipping line 2548: expected 10 fields, saw 11
Skipping line 2561: expected 10 fields, saw 14
Skipping line 2563: expected 10 fields, saw 15
Skipping line 2564: expected 10 fields, saw 15
Skipping line 2565: expected 10 fields, saw 11
Skipping line 2571: expected 10 fields, saw 13
Skipping line 2574: expected 10 fields, saw 20
Skipping line 2575: expected 10 fields, saw 14
Skipping line 2577: expected 10 fields, saw 12
Skipping line 2583: expected 10 fields, saw 12
Skipping line 2584: expected 10 fields, saw 13
Skipping line 2621: expected 10 fields, saw 15
Skipping line 2622: expected 10 fields, saw 12
Skipping line 2631: expected 10 fields, saw 13
Skipping line 2632: expected 10 fields, saw 12
Skipping line 2633: expected 10 fields, saw 12
Skipping line 2636: expected 10 fields, saw 11
Skipping line 2640: expected 10 fields, saw 11
Skipping line 2641: expected 10 fields, saw 11
Skipping line 2674: expected 10 fields, saw 11
Skipping line 2676: expected 10 fields, saw 16
Skipping line 2706: expected 10 fields, saw 14
Skipping line 2708: expected 10 fields, saw 12
Skipping line 2712: expected 10 fields, saw 17
Skipping line 2714: expected 10 fields, saw 13
Skipping line 2715: expected 10 fields, saw 13
Skipping line 2737: expected 10 fields, saw 11
Skipping line 2746: expected 10 fields, saw 11
Skipping line 2752: expected 10 fields, saw 11
Skipping line 2753: expected 10 fields, saw 15
Skipping line 2754: expected 10 fields, saw 11
Skipping line 2758: expected 10 fields, saw 15
Skipping line 2761: expected 10 fields, saw 12
Skipping line 2762: expected 10 fields, saw 23
Skipping line 2767: expected 10 fields, saw 11
Skipping line 2769: expected 10 fields, saw 13
Skipping line 2771: expected 10 fields, saw 11
Skipping line 2785: expected 10 fields, saw 14
Skipping line 2787: expected 10 fields, saw 12
Skipping line 2810: expected 10 fields, saw 19
Skipping line 2817: expected 10 fields, saw 11
Skipping line 2831: expected 10 fields, saw 11
Skipping line 2835: expected 10 fields, saw 13
Skipping line 2837: expected 10 fields, saw 25
Skipping line 2841: expected 10 fields, saw 13
Skipping line 2842: expected 10 fields, saw 11
Skipping line 2848: expected 10 fields, saw 11
Skipping line 2885: expected 10 fields, saw 13
Skipping line 2901: expected 10 fields, saw 11
Skipping line 2902: expected 10 fields, saw 12
Skipping line 2903: expected 10 fields, saw 11
Skipping line 2922: expected 10 fields, saw 11
Skipping line 2923: expected 10 fields, saw 12
Skipping line 2924: expected 10 fields, saw 11
Skipping line 2931: expected 10 fields, saw 12
Skipping line 2940: expected 10 fields, saw 11
Skipping line 2955: expected 10 fields, saw 17
Skipping line 2958: expected 10 fields, saw 11
Skipping line 2971: expected 10 fields, saw 12
Skipping line 2972: expected 10 fields, saw 11
Skipping line 2995: expected 10 fields, saw 12
Skipping line 2998: expected 10 fields, saw 13
Skipping line 2999: expected 10 fields, saw 14
Skipping line 3007: expected 10 fields, saw 16
Skipping line 3019: expected 10 fields, saw 11
Skipping line 3035: expected 10 fields, saw 11
Skipping line 3064: expected 10 fields, saw 11
Skipping line 3066: expected 10 fields, saw 19
Skipping line 3069: expected 10 fields, saw 11
Skipping line 3079: expected 10 fields, saw 13
Skipping line 3080: expected 10 fields, saw 12
Skipping line 3086: expected 10 fields, saw 17
Skipping line 3092: expected 10 fields, saw 11
Skipping line 3106: expected 10 fields, saw 11
Skipping line 3117: expected 10 fields, saw 12
Skipping line 3120: expected 10 fields, saw 11
Skipping line 3122: expected 10 fields, saw 16
Skipping line 3125: expected 10 fields, saw 29
Skipping line 3126: expected 10 fields, saw 11
Skipping line 3127: expected 10 fields, saw 14
Skipping line 3152: expected 10 fields, saw 12
Skipping line 3159: expected 10 fields, saw 24
Skipping line 3169: expected 10 fields, saw 15
Skipping line 3221: expected 10 fields, saw 14
Skipping line 3234: expected 10 fields, saw 13
Skipping line 3235: expected 10 fields, saw 12
Skipping line 3253: expected 10 fields, saw 11
Skipping line 3257: expected 10 fields, saw 13
Skipping line 3274: expected 10 fields, saw 12
Skipping line 3283: expected 10 fields, saw 12
Skipping line 3288: expected 10 fields, saw 11
Skipping line 3289: expected 10 fields, saw 14
Skipping line 3290: expected 10 fields, saw 15
Skipping line 3308: expected 10 fields, saw 11
Skipping line 3309: expected 10 fields, saw 13
Skipping line 3310: expected 10 fields, saw 13
Skipping line 3325: expected 10 fields, saw 13
Skipping line 3329: expected 10 fields, saw 11
Skipping line 3338: expected 10 fields, saw 17
Skipping line 3339: expected 10 fields, saw 11
Skipping line 3344: expected 10 fields, saw 15
Skipping line 3350: expected 10 fields, saw 11
Skipping line 3361: expected 10 fields, saw 15
Skipping line 3362: expected 10 fields, saw 11
Skipping line 3375: expected 10 fields, saw 13
Skipping line 3376: expected 10 fields, saw 12
Skipping line 3377: expected 10 fields, saw 12
Skipping line 3378: expected 10 fields, saw 16
Skipping line 3384: expected 10 fields, saw 14
Skipping line 3385: expected 10 fields, saw 17
Skipping line 3386: expected 10 fields, saw 11
Skipping line 3403: expected 10 fields, saw 14
Skipping line 3404: expected 10 fields, saw 13
Skipping line 3405: expected 10 fields, saw 18
Skipping line 3413: expected 10 fields, saw 16
Skipping line 3414: expected 10 fields, saw 13
Skipping line 3422: expected 10 fields, saw 11
Skipping line 3423: expected 10 fields, saw 13
Skipping line 3435: expected 10 fields, saw 13
Skipping line 3437: expected 10 fields, saw 14
Skipping line 3438: expected 10 fields, saw 13
Skipping line 3439: expected 10 fields, saw 11
Skipping line 3442: expected 10 fields, saw 11
Skipping line 3443: expected 10 fields, saw 11
Skipping line 3467: expected 10 fields, saw 12
Skipping line 3468: expected 10 fields, saw 29
Skipping line 3470: expected 10 fields, saw 12
Skipping line 3471: expected 10 fields, saw 24
Skipping line 3474: expected 10 fields, saw 17
Skipping line 3475: expected 10 fields, saw 11
Skipping line 3476: expected 10 fields, saw 12
Skipping line 3478: expected 10 fields, saw 14
Skipping line 3479: expected 10 fields, saw 17
Skipping line 3480: expected 10 fields, saw 11
Skipping line 3498: expected 10 fields, saw 15
Skipping line 3512: expected 10 fields, saw 16
Skipping line 3513: expected 10 fields, saw 13
Skipping line 3514: expected 10 fields, saw 13
Skipping line 3515: expected 10 fields, saw 12
Skipping line 3516: expected 10 fields, saw 14
Skipping line 3519: expected 10 fields, saw 15
Skipping line 3521: expected 10 fields, saw 13
Skipping line 3522: expected 10 fields, saw 17
Skipping line 3523: expected 10 fields, saw 11
Skipping line 3529: expected 10 fields, saw 12
Skipping line 3530: expected 10 fields, saw 23
Skipping line 3531: expected 10 fields, saw 13
Skipping line 3532: expected 10 fields, saw 12
Skipping line 3537: expected 10 fields, saw 13
Skipping line 3538: expected 10 fields, saw 26
Skipping line 3540: expected 10 fields, saw 12
Skipping line 3559: expected 10 fields, saw 13
Skipping line 3561: expected 10 fields, saw 11
Skipping line 3565: expected 10 fields, saw 12
Skipping line 3566: expected 10 fields, saw 25
Skipping line 3567: expected 10 fields, saw 11
Skipping line 3568: expected 10 fields, saw 21
Skipping line 3591: expected 10 fields, saw 12
Skipping line 3592: expected 10 fields, saw 12
Skipping line 3595: expected 10 fields, saw 14
Skipping line 3615: expected 10 fields, saw 12
Skipping line 3627: expected 10 fields, saw 12
Skipping line 3634: expected 10 fields, saw 17
Skipping line 3641: expected 10 fields, saw 11
Skipping line 3652: expected 10 fields, saw 12
Skipping line 3653: expected 10 fields, saw 13
Skipping line 3656: expected 10 fields, saw 15
Skipping line 3657: expected 10 fields, saw 12
Skipping line 3658: expected 10 fields, saw 22
Skipping line 3672: expected 10 fields, saw 11
Skipping line 3713: expected 10 fields, saw 19
Skipping line 3723: expected 10 fields, saw 11
Skipping line 3725: expected 10 fields, saw 13
Skipping line 3726: expected 10 fields, saw 14
Skipping line 3728: expected 10 fields, saw 12
Skipping line 3733: expected 10 fields, saw 14
Skipping line 3734: expected 10 fields, saw 12
Skipping line 3735: expected 10 fields, saw 15
Skipping line 3740: expected 10 fields, saw 11
Skipping line 3749: expected 10 fields, saw 12
Skipping line 3755: expected 10 fields, saw 11
Skipping line 3756: expected 10 fields, saw 12
Skipping line 3762: expected 10 fields, saw 11
Skipping line 3768: expected 10 fields, saw 13
Skipping line 3776: expected 10 fields, saw 12
Skipping line 3797: expected 10 fields, saw 11
Skipping line 3799: expected 10 fields, saw 11
Skipping line 3805: expected 10 fields, saw 12
Skipping line 3806: expected 10 fields, saw 12
Skipping line 3833: expected 10 fields, saw 12
Skipping line 3844: expected 10 fields, saw 22
Skipping line 3845: expected 10 fields, saw 12
Skipping line 3864: expected 10 fields, saw 19
Skipping line 3877: expected 10 fields, saw 11
Skipping line 3884: expected 10 fields, saw 13
Skipping line 3887: expected 10 fields, saw 18
Skipping line 3889: expected 10 fields, saw 11
Skipping line 3903: expected 10 fields, saw 13
Skipping line 3908: expected 10 fields, saw 12
Skipping line 3917: expected 10 fields, saw 12
Skipping line 3918: expected 10 fields, saw 12
Skipping line 3919: expected 10 fields, saw 17
Skipping line 3926: expected 10 fields, saw 13
Skipping line 3927: expected 10 fields, saw 12
Skipping line 3928: expected 10 fields, saw 11
Skipping line 3946: expected 10 fields, saw 12
Skipping line 3953: expected 10 fields, saw 12
Skipping line 3954: expected 10 fields, saw 11
Skipping line 3955: expected 10 fields, saw 11
Skipping line 3956: expected 10 fields, saw 14
Skipping line 3957: expected 10 fields, saw 11
Skipping line 3959: expected 10 fields, saw 17
Skipping line 3967: expected 10 fields, saw 16
Skipping line 3975: expected 10 fields, saw 11
Skipping line 3976: expected 10 fields, saw 12
Skipping line 3981: expected 10 fields, saw 14
Skipping line 3994: expected 10 fields, saw 14
Skipping line 3997: expected 10 fields, saw 11
Skipping line 4004: expected 10 fields, saw 11
Skipping line 4014: expected 10 fields, saw 12
Skipping line 4015: expected 10 fields, saw 12
Skipping line 4020: expected 10 fields, saw 11
Skipping line 4035: expected 10 fields, saw 11
Skipping line 4041: expected 10 fields, saw 16
Skipping line 4042: expected 10 fields, saw 12
Skipping line 4050: expected 10 fields, saw 20
Skipping line 4051: expected 10 fields, saw 11
Skipping line 4052: expected 10 fields, saw 13
Skipping line 4054: expected 10 fields, saw 11
Skipping line 4055: expected 10 fields, saw 12
Skipping line 4064: expected 10 fields, saw 11
Skipping line 4066: expected 10 fields, saw 11
Skipping line 4067: expected 10 fields, saw 14
Skipping line 4068: expected 10 fields, saw 11
Skipping line 4069: expected 10 fields, saw 11
Skipping line 4070: expected 10 fields, saw 11
Skipping line 4072: expected 10 fields, saw 11
Skipping line 4090: expected 10 fields, saw 15
Skipping line 4091: expected 10 fields, saw 14
Skipping line 4107: expected 10 fields, saw 13
Skipping line 4119: expected 10 fields, saw 13
Skipping line 4120: expected 10 fields, saw 17
Skipping line 4121: expected 10 fields, saw 11
Skipping line 4122: expected 10 fields, saw 12
Skipping line 4126: expected 10 fields, saw 12
Skipping line 4127: expected 10 fields, saw 11
Skipping line 4130: expected 10 fields, saw 18
Skipping line 4131: expected 10 fields, saw 12
Skipping line 4132: expected 10 fields, saw 12
Skipping line 4138: expected 10 fields, saw 12
Skipping line 4140: expected 10 fields, saw 12
Skipping line 4170: expected 10 fields, saw 13
Skipping line 4173: expected 10 fields, saw 17
Skipping line 4180: expected 10 fields, saw 13
Skipping line 4197: expected 10 fields, saw 13
Skipping line 4214: expected 10 fields, saw 16
Skipping line 4242: expected 10 fields, saw 17
Skipping line 4249: expected 10 fields, saw 11
Skipping line 4250: expected 10 fields, saw 22
Skipping line 4257: expected 10 fields, saw 11
Skipping line 4258: expected 10 fields, saw 11
Skipping line 4259: expected 10 fields, saw 12
Skipping line 4261: expected 10 fields, saw 13
Skipping line 4267: expected 10 fields, saw 11
Skipping line 4268: expected 10 fields, saw 14
Skipping line 4277: expected 10 fields, saw 11
Skipping line 4282: expected 10 fields, saw 20
Skipping line 4283: expected 10 fields, saw 17
Skipping line 4285: expected 10 fields, saw 14
Skipping line 4286: expected 10 fields, saw 18
Skipping line 4288: expected 10 fields, saw 11
Skipping line 4305: expected 10 fields, saw 12
Skipping line 4308: expected 10 fields, saw 15
Skipping line 4310: expected 10 fields, saw 12
Skipping line 4312: expected 10 fields, saw 12
Skipping line 4313: expected 10 fields, saw 11
Skipping line 4314: expected 10 fields, saw 12
Skipping line 4324: expected 10 fields, saw 17
Skipping line 4329: expected 10 fields, saw 12
Skipping line 4330: expected 10 fields, saw 17
Skipping line 4336: expected 10 fields, saw 12
Skipping line 4352: expected 10 fields, saw 11
Skipping line 4353: expected 10 fields, saw 13
Skipping line 4375: expected 10 fields, saw 11
Skipping line 4377: expected 10 fields, saw 12
Skipping line 4378: expected 10 fields, saw 12
Skipping line 4383: expected 10 fields, saw 11
Skipping line 4409: expected 10 fields, saw 15
Skipping line 4418: expected 10 fields, saw 11
Skipping line 4419: expected 10 fields, saw 11
Skipping line 4421: expected 10 fields, saw 13
Skipping line 4443: expected 10 fields, saw 12
Skipping line 4445: expected 10 fields, saw 13
Skipping line 4450: expected 10 fields, saw 11
Skipping line 4452: expected 10 fields, saw 12
Skipping line 4455: expected 10 fields, saw 12
Skipping line 4456: expected 10 fields, saw 11
Skipping line 4464: expected 10 fields, saw 14
Skipping line 4487: expected 10 fields, saw 12
Skipping line 4494: expected 10 fields, saw 15
Skipping line 4495: expected 10 fields, saw 13
Skipping line 4503: expected 10 fields, saw 11
Skipping line 4504: expected 10 fields, saw 11
Skipping line 4505: expected 10 fields, saw 18
Skipping line 4527: expected 10 fields, saw 12
Skipping line 4563: expected 10 fields, saw 11
Skipping line 4564: expected 10 fields, saw 24
Skipping line 4565: expected 10 fields, saw 11
Skipping line 4577: expected 10 fields, saw 12
Skipping line 4578: expected 10 fields, saw 14
Skipping line 4589: expected 10 fields, saw 13
Skipping line 4605: expected 10 fields, saw 15
Skipping line 4606: expected 10 fields, saw 12
Skipping line 4607: expected 10 fields, saw 16
Skipping line 4608: expected 10 fields, saw 19
Skipping line 4609: expected 10 fields, saw 11
Skipping line 4626: expected 10 fields, saw 11
Skipping line 4632: expected 10 fields, saw 13
Skipping line 4641: expected 10 fields, saw 13
Skipping line 4658: expected 10 fields, saw 35
Skipping line 4659: expected 10 fields, saw 12
Skipping line 4660: expected 10 fields, saw 11
Skipping line 4665: expected 10 fields, saw 11
Skipping line 4670: expected 10 fields, saw 14
Skipping line 4690: expected 10 fields, saw 11
Skipping line 4695: expected 10 fields, saw 14
Skipping line 4722: expected 10 fields, saw 13
Skipping line 4729: expected 10 fields, saw 11
Skipping line 4730: expected 10 fields, saw 12
Skipping line 4741: expected 10 fields, saw 12
Skipping line 4742: expected 10 fields, saw 11
Skipping line 4764: expected 10 fields, saw 12
Skipping line 4765: expected 10 fields, saw 13
Skipping line 4775: expected 10 fields, saw 11
Skipping line 4776: expected 10 fields, saw 11
Skipping line 4777: expected 10 fields, saw 11
Skipping line 4781: expected 10 fields, saw 28
Skipping line 4782: expected 10 fields, saw 11
Skipping line 4784: expected 10 fields, saw 11
Skipping line 4786: expected 10 fields, saw 11
Skipping line 4787: expected 10 fields, saw 20
Skipping line 4788: expected 10 fields, saw 11
Skipping line 4801: expected 10 fields, saw 11
Skipping line 4802: expected 10 fields, saw 27
Skipping line 4803: expected 10 fields, saw 11
Skipping line 4804: expected 10 fields, saw 18
Skipping line 4806: expected 10 fields, saw 12
Skipping line 4808: expected 10 fields, saw 16
Skipping line 4809: expected 10 fields, saw 11
Skipping line 4825: expected 10 fields, saw 17
Skipping line 4833: expected 10 fields, saw 11
Skipping line 4839: expected 10 fields, saw 13
Skipping line 4840: expected 10 fields, saw 12
Skipping line 4854: expected 10 fields, saw 11
Skipping line 4856: expected 10 fields, saw 19
Skipping line 4859: expected 10 fields, saw 12
Skipping line 4860: expected 10 fields, saw 11
Skipping line 4861: expected 10 fields, saw 12
Skipping line 4862: expected 10 fields, saw 12
Skipping line 4863: expected 10 fields, saw 11
Skipping line 4864: expected 10 fields, saw 14
Skipping line 4865: expected 10 fields, saw 15
Skipping line 4866: expected 10 fields, saw 11
Skipping line 4870: expected 10 fields, saw 14
Skipping line 4878: expected 10 fields, saw 12
Skipping line 4880: expected 10 fields, saw 14
Skipping line 4881: expected 10 fields, saw 12
Skipping line 4891: expected 10 fields, saw 11
Skipping line 4896: expected 10 fields, saw 11
Skipping line 4897: expected 10 fields, saw 11
Skipping line 4909: expected 10 fields, saw 14
Skipping line 4911: expected 10 fields, saw 11
Skipping line 4912: expected 10 fields, saw 12
Skipping line 4918: expected 10 fields, saw 20
Skipping line 4919: expected 10 fields, saw 11
Skipping line 4922: expected 10 fields, saw 20
Skipping line 4924: expected 10 fields, saw 11

In [ ]:
# preview the data
df.head()

,Unnamed: 0,business_id,cool,date,funny,review_id,stars,text,useful,user_id
0,1,pomGBqfbxcqPv14c3XH-ZQ,0,2012-11-13,0,dDl8zu1vWPdKGihJrwQbpw,5,I love this place! My fiance And I go here atl...,0,msQe1u7Z_XuqjGoqhB0J5g
1,2,jtQARsP6P-LbkyjbO1qNGg,1,2014-10-23,1,LZp4UX5zK3e-c5ZGSeo3kA,1,Terrible. Dry corn bread. Rib tips were all fa...,3,msQe1u7Z_XuqjGoqhB0J5g
2,4,Ums3gaP2qM3W1XcA5r6SsQ,0,2014-09-05,0,jsDu6QEJHbwP2Blom1PLCA,5,Delicious healthy food. The steak is amazing. ...,0,msQe1u7Z_XuqjGoqhB0J5g
3,5,vgfcTvK81oD4r50NMjU2Ag,0,2011-02-25,0,pfavA0hr3nyqO61oupj-lA,1,This place sucks. The customer service is horr...,2,msQe1u7Z_XuqjGoqhB0J5g
4,10,yFumR3CWzpfvTH2FCthvVw,0,2016-06-15,0,STiFMww2z31siPY7BWNC2g,5,I have been an Emerald Club member for a numbe...,0,TlvV-xJhmh7LCwJYXkV-cg

In [ ]:
# index of the data
df.index

RangeIndex(start=0, stop=4035, step=1)

In [ ]:
# preview a row in the chaos
df.iloc[1965]

Unnamed: 0     And the french toast fries.....OMG so good! St...
business_id                                                    0
cool                                      0pf5VuzE4_1pwj5NJHG5TQ
date                                                         NaN
funny                                                        NaN
review_id                                                    NaN
stars                                                        NaN
text                                                         NaN
useful                                                       NaN
user_id                                                      NaN
Name: 1965, dtype: object

In [ ]:
# brief description of the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4035 entries, 0 to 4034
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   4035 non-null   object
 1   business_id  3293 non-null   object
 2   cool         3097 non-null   object
 3   date         2495 non-null   object
 4   funny        2284 non-null   object
 5   review_id    2194 non-null   object
 6   stars        2127 non-null   object
 7   text         2072 non-null   object
 8   useful       1640 non-null   object
 9   user_id      1525 non-null   object
dtypes: object(10)
memory usage: 315.4+ KB

Most definilitely this data would need a lot of cleaning!!

When we come across poorly formatted data, one common issue arises when strings within a CSV file contain commas. According to the standard protocol, we address this by using quotes to distinguish between the commas that denote fields and the commas within those fields. For instance:

Original (without quotes):
```
ReviewerID,Rating,N_reviews,Review,VenueID,123456,4,137,This restaurant was pretty good, we had a great time.,98765
```

Formatted (with quotes):
```
"ReviewerID","Rating","N_reviews","Review","VenueID","123456","4","137","This restaurant was pretty good, we had a great time.","98765"
```

## Reading Excel Files with Pandas (`pd.read_excel`):

Reading Excel files into Pandas DataFrames is a common operation in data analysis. The `pd.read_excel` function provides a convenient way to accomplish this task. Let's explore the function along with some of its most commonly used parameters:

### Basic Usage (Default Parameters)

In [ ]:
# Reading an Excel file
df = pd.read_excel('Yelp_Selected_Businesses.xlsx')
df.head()

,business_id,cool,date,funny,review_id,stars,text,useful,user_id
0,RESDUcs7fIiihp38-d6_6g,0,2015-09-16,0,gkcPdbblTvZDMSwx8nVEKw,5,Got here early on football Sunday 7:30am as I ...,0,SKteB5rgDlkkUa1Zxe1N0Q
1,RESDUcs7fIiihp38-d6_6g,0,2017-09-09,0,mQfl6ci46mu0xaZrkRUhlA,5,"This buffet is amazing. Yes, it is expensive,...",0,f638AHA_GoHbyDB7VFMz7A
2,RESDUcs7fIiihp38-d6_6g,0,2013-01-14,0,EJ7DJ8bm7-2PLFB9WKx4LQ,3,I was really looking forward to this but it wa...,0,-wVPuTiIEG85LwTK46Prpw
3,RESDUcs7fIiihp38-d6_6g,0,2017-02-08,0,lMarDJDg4-e_0YoJOKJoWA,2,This place....lol our server was nice. But fo...,0,A21zMqdN76ueLZFpmbue0Q
4,RESDUcs7fIiihp38-d6_6g,0,2012-11-19,0,nq_-8lZPUVGomDEP5OOj1Q,1,"After hearing all the buzz about this place, I...",2,Jf1EXieUV7F7s-HGA4EsdA

The `pd.read_excel` function is straightforward and reads the first sheet of the Excel file by default.

### Specifying Sheet Name

In [ ]:
# Reading a specific sheet from an Excel file
df_sheet2 = pd.read_excel('Yelp_Selected_Businesses.xlsx', sheet_name='Biz_id_4JNXU')
df_sheet2.head()

,business_id,cool,date,funny,review_id,stars,text,useful,user_id
0,4JNXUYY8wbaaDmk3BPzlWw,0,2012-06-10,0,wl8BO_I-is-JaMwMW5c_gQ,4,I booked a table here for brunch and it did no...,0,fo4mpUqgXL2mJqALc9AvbA
1,4JNXUYY8wbaaDmk3BPzlWw,0,2012-01-20,0,cf9RrqHY9eQ9M53OPyXLtg,4,Came here for lunch after a long night of part...,0,TVvTtXwPXsvrg2KJGoOUTg
2,4JNXUYY8wbaaDmk3BPzlWw,0,2017-05-10,0,BvmhSQ6WFm2Jxu01G8OpdQ,5,Loved the fried goat cheese in tomato sauce al...,0,etbAVunw-4kwr6VTRweZpA
3,4JNXUYY8wbaaDmk3BPzlWw,0,2014-05-03,0,IoKp9n1489XohTV_-EJ0IQ,5,"Love the outdoor atmosphere. Price was right, ...",0,vKXux2Xx3xcicTgYZoR0pg
4,4JNXUYY8wbaaDmk3BPzlWw,0,2014-06-04,0,7YNmSq7Lb1zi4SUKXaSjfg,5,Best steak in Vegas. Best mashed potatoes in V...,3,e3s1x4LLqfSkRTWDy_-Urg

We can use the `sheet_name` parameter to specify the sheet we want to read.

### Reading Multiple Sheets

In [ ]:
# Reading multiple sheets from an Excel file
sheets_dict = pd.read_excel('Yelp_Selected_Businesses.xlsx', sheet_name=['Biz_id_4JNXU', 'Biz_id_YJ8lj'])

type(sheets_dict)

dict

In [ ]:
sheets_dict.keys()

dict_keys(['Biz_id_4JNXU', 'Biz_id_YJ8lj'])

In [ ]:
# preview firs five rows of the second sheet
sheets_dict['Biz_id_YJ8lj']

,business_id,cool,date,funny,review_id,stars,text,useful,user_id
0,YJ8ljUhLsz6CtT_2ORNFmg,1,2013-04-25,0,xgUz0Ck4_ciNaeIk-H8GBQ,5,I loved this place. Easily the most hipsters p...,1,6cpo8iqgnW3jnozhmY7eAA
1,YJ8ljUhLsz6CtT_2ORNFmg,0,2014-07-07,0,Au7MG4QlAxqq9meyKSQmaw,5,So my boyfriend and I came here for my birthda...,0,8bFE3u1dMoYXkS7ORqlssw
2,YJ8ljUhLsz6CtT_2ORNFmg,0,2015-12-04,0,8IQnZ54nenXjlK-FGZ82Bg,5,I really enjoyed their food. Went there for th...,1,bJmE1ms0MyZ6KHjmfZDWGw
3,YJ8ljUhLsz6CtT_2ORNFmg,2,2016-07-06,1,XY42LMhKoXzwtLoku4mvLA,5,A complete Vegas experience. We arrived right ...,3,PbccpC-I-8rxzF2bCDh8YA
4,YJ8ljUhLsz6CtT_2ORNFmg,0,2014-04-15,0,1xlYVWhyLedoA0HddOJMOw,4,Very great atmosphere had a wonderful bartende...,0,yvlRColhqo_4TzpUFKyroA

Provide a list of sheet names or None to read all sheets into a dictionary of DataFrames.

### Handling Headers and Skipped Rows

In [ ]:
# Specifying header and skipping rows
df_skip_rows = pd.read_excel('Yelp_Selected_Businesses.xlsx', sheet_name='Biz_id_YJ8lj', header=0, skiprows=[2, 3])
df_skip_rows

,business_id,cool,date,funny,review_id,stars,text,useful,user_id
0,YJ8ljUhLsz6CtT_2ORNFmg,1,2013-04-25,0,xgUz0Ck4_ciNaeIk-H8GBQ,5,I loved this place. Easily the most hipsters p...,1,6cpo8iqgnW3jnozhmY7eAA
1,YJ8ljUhLsz6CtT_2ORNFmg,2,2016-07-06,1,XY42LMhKoXzwtLoku4mvLA,5,A complete Vegas experience. We arrived right ...,3,PbccpC-I-8rxzF2bCDh8YA
2,YJ8ljUhLsz6CtT_2ORNFmg,0,2014-04-15,0,1xlYVWhyLedoA0HddOJMOw,4,Very great atmosphere had a wonderful bartende...,0,yvlRColhqo_4TzpUFKyroA

Use `header` to specify the row to use as headers and `skiprows` to skip specific rows.

### Specifying Columns to Read

In [ ]:
# Reading specific columns from an Excel file
df_columns = pd.read_excel('Yelp_Selected_Businesses.xlsx', usecols=['date', 'text', 'user_id'])
df_columns

,date,text,user_id
0,2015-09-16,Got here early on football Sunday 7:30am as I ...,SKteB5rgDlkkUa1Zxe1N0Q
1,2017-09-09,"This buffet is amazing. Yes, it is expensive,...",f638AHA_GoHbyDB7VFMz7A
2,2013-01-14,I was really looking forward to this but it wa...,-wVPuTiIEG85LwTK46Prpw
3,2017-02-08,This place....lol our server was nice. But fo...,A21zMqdN76ueLZFpmbue0Q
4,2012-11-19,"After hearing all the buzz about this place, I...",Jf1EXieUV7F7s-HGA4EsdA
5,2012-10-31,Good food. Slow to get in even when there's p...,INbqkFXtHeCdEP_wPp2dUA
6,2014-04-15,Best Buffet I experienced in Vegas! You have t...,yvlRColhqo_4TzpUFKyroA
7,2017-12-22,One star knocked off for the cold air conditio...,uNHEnP28MMmVy96ZSJKaMA

The `usecols` parameter allows you to select specific columns to read.

By mastering these parameters, we can efficiently read Excel files into Pandas DataFrames while addressing various scenarios and customizing the import process based on your specific requirements.

## Saving Data

Once we have data loaded that we may want to export back out, we use the `.to_csv()` or `.to_excel()` methods of any DataFrame object.

In [ ]:
# Write data to a CSV file

# Notice how we have to pass index=False if we do not want it included in our output

df_columns.to_csv('NewSavedView.csv', index=False)

In [ ]:
# Write data to an Excel file

df_columns.to_excel('NewSavedView.xlsx')

## Summary

Excellent! In this lesson, we've fortified our proficiency in importing data with Pandas, an essential skill for any data analyst. Whether we're dealing with CSV, Excel, JSON, SQL, or other data file formats, the principles and functions remain remarkably consistent. The `pd.read_csv()` and `pd.read_excel()` functions, for instance, share similar parameters, allowing us to seamlessly navigate through diverse datasets. We've uncovered the art of handling challenging scenarios, such as ill-formatted data with strings containing commas, and gained insights into customizing the import process with parameters like `skiprows`, `header`, `encoding`, and `index_col`.

As we transcend this lesson, armed with the ability to efficiently read and manipulate data, we recognize the universality of these skills. The knowledge gained here transcends file formats, laying a solid foundation for approaching any data source with confidence. Whether it's a JSON file, a SQL database, or another data file, the familiarity with Pandas functions and their consistent parameters empowers us to tackle diverse datasets with ease, opening doors to more advanced data analysis endeavors in our data science journey.